{"user":{"stdout":["id.onError:  Error: ups\n    at E:\\work\\repos\\jawis\\packages\\tests\\all\\jab-node mainWrapper err 1.wo.ts:7:9\n    at Object.mainWrapper (E:\\work\\repos\\jawis\\packages\\jab-node\\jagoMainProv.ts:232:5)\n    at Object.<anonymous> (E:\\work\\repos\\jawis\\packages\\tests\\all\\jab-node mainWrapper err 1.wo.ts:5:1)\n    at Module._compile (internal/modules/cjs/loader.js:1158:30)\n    at Module._compile (E:\\work\\repos\\jawis\\node_modules\\source-map-support\\source-map-support.js:547:25)\n    at Object.<anonymous> (E:\\work\\repos\\jawis\\node_modules\\@wistoft\\jacs\\compiled\\webpack:\\packages\\jab-node\\node-module-util.ts:159:19)\n    at Module.load (internal/modules/cjs/loader.js:1002:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:901:14)\n    at Module.require (internal/modules/cjs/loader.js:1044:19)\n    at require (internal/modules/cjs/helpers.js:77:18) \n [\n.\tuh-exception\n]\nfinally done\n"]}}