{"user":{"stdout":["id.onError:  Error: ups\n    at E:\\work\\repos\\jawis\\packages\\tests\\cur2\\jab-node mainWrapper err 1.pr.ts:7:11\n    at Object.mainWrapper (E:\\work\\repos\\jawis\\packages\\jab-node\\jagoMainProv.ts:232:5)\n    at Object.<anonymous> (E:\\work\\repos\\jawis\\packages\\tests\\cur2\\jab-node mainWrapper err 1.pr.ts:5:13)\n    at Module._compile (internal/modules/cjs/loader.js:1158:30)\n    at Module.m._compile (E:\\work\\repos\\jawis\\node_modules\\ts-node\\src\\index.ts:858:23)\n    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)\n    at Object.require.extensions.<computed> [as .ts] (E:\\work\\repos\\jawis\\node_modules\\ts-node\\src\\index.ts:861:12)\n    at Module.load (internal/modules/cjs/loader.js:1002:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:901:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) \n [\n.\tuh-exception\n]\nfinally done\n"]}}